### ISSUE TITLE
Crash with Grimpack mod upon startup

### ISSUE THREAD

**Issue by Velocihater** [duely/dwmh#85]
https://paste.dimdev.org/yejumuxehu.mccrash

**Comment by duely** [comment]
That's a rather strange one, looking into it!

**Comment by duely** [comment]
That is a really strange one. It looks as though an entity is actually being created during the init process, and when it's attempting to gather capabilities, my code (which hasn't been fully initialized yet) is called. Can you try the jar from this hotfix zip and tell me if that fixes it for you? [dwmh-2.1.0-hotfix.zip](https://github.com/duely/dwmh/files/3001177/dwmh-2.1.0-hotfix.zip)

**Comment by duely** [comment]
Actually, that should fix it regardless, I'll push out a hotfix.

**Comment by duely** [comment]
The [2.1.1 hotfix is now available on CurseForge](https://minecraft.curseforge.com/projects/dude-wheres-my-horse/files/2691456).
