### ISSUE TITLE
primitive mobs compatibility

### ISSUE THREAD

**Issue by lag42** [duely/dwmh#86]
in primitive mobs if you feed a pet baby spider you got from a spider egg 5 fermented spider eyes it will grow and you can mount it, i think that meets the requirements of being a steed and therefore should get compatibility

**Comment by duely** [comment]
I'm currently rewriting the entire code base to allow for much more flexible use of the ocarina, which will allow you (theoretically) to summon the spider mount. I'll have to ensure that this edge case is considered as it would technically be a hostile mob. Thanks for the idea!

**Comment by duely** [comment]
Hopefully the new version (3) makes this a possibility! Please let me know if it doesn't work: it may still be registering the spider as a hostile creature.

**Comment by lag42** [comment]
i finally tried 3.0.0 and it didn't work on the spiders, sorry it took 3 days for me to get back to you on this

**Comment by duely** [comment]
All right, I've specifically added a whitelist of monsters that automatically have baby spiders added. Unfortunately this does allow you to summon hostile baby spiders, but it's difficult to agnostically determine whether it is tame or not without specialcasing.
