### ISSUE TITLE
Crash with Dragon Mounts 2

### ISSUE THREAD

**Issue by BrisingrAerowing** [duely/dwmh#87]
[Crash Log](https://paste.dimdev.org/qegobezedu.mccrash)

**Comment by duely** [comment]
Ouch! Yeah, this is something that was bound to happen eventually. In the meantime, you can disable the Dragon Mounts 2 module in the configuration and it will allow you to play the game, although Dragon Mounts 2 entities will not be summonable.

I'm currently working on a major rewrite to address this issue and to simplify the concept & codebase.

**Comment by BrisingrAerowing** [comment]
As a side note, Ice and Fire has an Ampithere, which also acts as a steed. You may want to add that to the config by default.

**Comment by duely** [comment]
Version 3 should hopefully resolve all of these. There is always the possibility that creatures flagged as monsters may not be taggable with the ocarina; if that's the case, please open an issue here so I can explore it further.
