### ISSUE TITLE
Suggestion for unloaded chunks

### ISSUE THREAD

**Issue by OCDCleric** [duely/dwmh#92]
I was thinking about how we lose the horse in unloaded chunks and then I thought, why not have the horse despawn?

So my suggestion is like this. Why not store the NBT data of the horse/mob onto the ocarina? The mob can then simply despawn and the mob can then be "summoned" to the player location. If the player tries to "summon" the mob while its still loaded nearby, the mob should be despawned and spawned next to player.

**Comment by duely** [comment]
In the most recent release for 1.12.2, this is indeed how the Ocarina works! I'm currently working on porting this code to 1.14.4, which is taking a little while as it's more complex and I'm not as familiar with the 1.14.4 code base.
